### ISSUE TITLE
Improve Compatible With Other Toolbar Panels

### ISSUE THREAD

**Issue by wsqamo** [Christian1984/vfrmap-for-vr#15]
It's a great app, but how can it be used with other toolbars, such as bushtalk radio, simbrief panel, FSPM vfrmap, and so on, compatible with multiple toolbars

**Comment by Christian1984** [comment]
Hi wsqamo and thanks for reaching out. I am aware of the issue. Unfortunately, I haven't identified the exact cause for the issue. Do the other panels that you mentioned work together without crashing the sim? For example, can you run FSPM vfrmap and bushtalk radio, for example, together?

If anyone of you guys out there would like to investigate the issue further, please feel free to do so and file a PR. Otherwise I'll look into it as soon as I can!

**Comment by wsqamo** [comment]
Yes, I tried several toolbars I listed one by one with exclusion and combination methods. Using them individually or simultaneously did not cause problems for the simulator, but as long as you put vfrmap for VR, you can't load the flight normally, unless you use it alone. By the way, the previous versions of bushtalkradio also had problems that they can't be used together with other toolbars, Later, the updated version was fixed. I don't understand professional things, but I think you can try to contact the author of similar problems to see if there is a solution.

**Comment by Christian1984** [comment]
Fixed!

I will release hotfix 1.2.1 ASAP, probably tomorrow!

Thanks to @wsqamo for bringing my attention to bushtalkradio. I spoke to the author this afternoon and compared his v1.1 with his v1.2 which in combination helped me get the issue sorted out.

BIG THANK YOU!!!

![fskneeboard-compatible-with-other-panels](https://user-images.githubusercontent.com/5574632/119842478-01c07b00-bf07-11eb-9bf5-3471bea72805.PNG)
