### ISSUE TITLE
Opens every time change view back to cockpit

### ISSUE THREAD

**Issue by Raging-Beard** [Christian1984/vfrmap-for-vr#22]
If I turn it off by hotkey, changing view to external or drone causes it to reopen again upon switching back to interior view.

**Comment by Christian1984** [comment]
That is correct and caused by the "hacky" nature of how the hotkey feature works internally. Please note that the feature is still experimental. For the time being, I have no idea how to really fix this other than implementing a natove MSFS hotkey, which I haven't found any documentation about, yet.
