### ISSUE TITLE
Notetaking via Keyboard

### ISSUE THREAD

**Issue by thedutchguy92** [Christian1984/vfrmap-for-vr#8]
Great app! i have the pro version and it works like a charm. one request though if possible. could you make the notepad also typable. so top half is writable and bottom half is typable? i find that typing frequenties is a lot faster than writing them.

**Comment by Christian1984** [comment]
Hey there. I had something like this on my mind, but wasn't sure how helpful it would be.

How do you use your keyboard when you are in VR? I'm very used to my keyboard and don't really have to look at it. However, when in VR, I find it quite hard to type anything, to be honest :-)

But when I get you right, you'd say that typing inside VR works good enough for you? Or are you considering a "software keyboard", i.e. keys that you'd click inside VR with your mouse?

**Comment by thedutchguy92** [comment]
Hey Christian, 

I agree with you that the keyboard itself isn't that useful. But, the numpad is. Especially for radio frequencies, headings and altitudes. The things you mostly get when flying in vatsim. For initial IFR clearance I would use the mouse writing option. But for inflight clearances (altitude etc.) it would be great if you could quickly click on the kneeboard and punch in a couple of numbers instead of writing them with the mouse.

**Comment by OY-4671** [comment]
Great App, much appreciated for VR. I downloaded this version today and are waiting for Pro access :-) , have used VRmap for a while. I have a thought about how great it would be to strap a Wacom drawing tablet (or another brand) to leg and be able to write with a pen on a notepad inside VR.  The pen has buttons that can be bound as mouse buttons, so I think this can be used to control all functions in the kneeboard app aswell.  I'm not advertising for Wacom, its just the only one I know of because these are the ones my daughter are using. This is an example.   https://www.wacom.com/en-dk/products/one-by-wacom
EDIT: I have had some time to try it now, and it is working with the tablet. it is perfect! ok, there is a small learning curve getting used to the tablet straped to my leg, but damn it is a must have :-) 
The only comment I have is regarding the map. Zoom buttons like on the middle tab, would be nice to have..

**Comment by OY-4671** [comment]
I just saw your YT video about V1.2.0 - Thank you for the zoom function. Now I can't wait to get home and try the new features. The  waypoints you added last time is awesome, so nice that we are able to put in new waypoints with new course in flight, when we deviate from intended course. This is going to be one of the best and most usefull add-ons for VFR in VR. I payed to little for the pro version, but that I will make up for. Very nice to see how serious you seem to be about it.
One thing I have noticed, is when I plot in a course or point when in monitor mode, it does not remember the route when switching to VR. This could be usefull when copying af task from NeoFly to Kneeboard. Perhaps that is allready fixed in regards to the "memory" of map placing you mentioned in the video?
EDIT: I misundestood the "scale" function for zoom.. But that is also an appreciated feature :-) Hoping for Zoom buttons on map.
I tried to setup a route in monitor mode in V1.2.0 and lost it when switched to VR.. something for the wishlist :-)

**Comment by lexmirnov** [comment]
I can blind type, so I really would like to see keyboard input implemented

**Comment by andyanfieldroad** [comment]
I personally would love it if the notepad had an on-screen keyboard down the bottom like your phone does.  Click on the notepad screen to place the cursor and type away.

**Comment by Christian1984** [comment]
You mean like that? https://discord.com/channels/849188204426690562/850776119963287593/941629478407389255 :-) It's "fresh off the press" and will be released soon with v1.6 - Physical keyboard inputs work as well, but might interfere with MSFS hotkeys (think typing "G" and your landing gear might retract)...

**Comment by Christian1984** [comment]
Implemented. To be released with v1.6
